@echo off
echo ==== Copying RAM images for debugging...
xcopy /Y dist\*.dcpu16 ..\%1
echo ==== Setting up distribution...
if not exist ..\%1\dist mkdir ..\%1\dist
if not exist ..\%1\dist\emulator mkdir ..\%1\dist\emulator
if not exist ..\%1\dist\emulator\examples mkdir ..\%1\dist\emulator\examples
echo ==== Copying RAM images for distribution...
xcopy /Y dist\*.dcpu16 ..\%1\dist\emulator\examples
echo ==== Copying libraries for distribution...
xcopy /Y ..\%1\SDL.dll ..\%1\dist\emulator
xcopy /Y ..\%1\libtcod-VS.dll ..\%1\dist\emulator
xcopy /Y ..\%1\zlib1.dll ..\%1\dist\emulator
xcopy /Y ..\%1\terminal.png ..\%1\dist\emulator
echo ==== Copying executables for distribution...
xcopy /Y ..\%1\emulator.exe ..\%1\dist\emulator