#line 2 "lexer.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
static yyconst short int yy_accept[204] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       93,   92,   91,   89,   92,   92,   88,   84,   79,   92,
       81,   81,   87,   90,   79,   85,   86,    8,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,    9,   43,   44,   45,   49,   50,   46,   47,
       48,   52,   53,   54,   58,   59,   55,   56,   57,   61,
       62,   63,   67,   68,   92,   64,   65,   66,   91,    0,
       83,    0,    0,    0,   79,   79,    0,    0,    0,    0,
        0,    0,   81,    0,   90,    0,    0,    0,    0,    0,
        0,    0,    0,   76,    0,   77,    0,    0,    0,    0,

        0,    0,    0,    0,   75,    0,    0,    0,    0,    0,
        0,    0,   74,    0,    0,    0,    0,   82,    0,    0,
        0,    0,    0,    0,    0,   80,   11,   33,   18,   22,
       19,   15,   16,   41,   39,   40,   37,   38,   30,   25,
       26,   27,   29,   31,   28,   32,   36,   35,   14,   17,
       13,   24,   78,    0,    0,   70,    0,    0,   10,   23,
       21,   12,   34,    0,   20,   69,    0,    0,    0,    0,
        0,    4,    0,   60,   72,   73,   71,   42,   51,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    6,    0,    7,    5,    3,    0,    0,    1,

        0,    2,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    1,    1,    1,    1,    6,    1,
        1,    1,    7,    8,    9,   10,    1,   11,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,    1,
        1,    1,    1,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,    1,    9,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,   24,   25,   44,   27,   28,
       45,   30,   31,   46,   33,   34,   35,   36,   37,   47,
       39,   40,   48,    1,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[50] =
    {   0,
        1,    1,    2,    2,    1,    3,    1,    1,    4,    1,
        5,    5,    1,    1,    5,    5,    5,    5,    5,    5,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    1,    1,    4,    4,    4,    4,    1,    1
    } ;

static yyconst short int yy_base[212] =
    {   0,
        0,   49,   84,  119,  154,    0,  189,  222,  255,    0,
      276,  362,  273,  362,    4,  232,  362,  362,    4,   48,
       11,    6,  362,    0,   19,  362,  362,  362,    1,   36,
        4,    0,  236,   17,  235,   43,   35,   51,  248,   91,
      251,   56,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  242,  362,  362,  362,  262,   34,
      362,  260,   77,   30,    9,    0,   60,   57,   96,   83,
       86,   93,  116,    0,    0,  131,  217,  136,  240,  112,
      113,  221,  233,  362,  125,  129,  288,  221,  129,  231,

      235,   40,  229,  217,  362,  231,  232,  218,  214,  223,
      209,  153,  362,  144,  137,  140,  208,  362,  206,  146,
      210,  218,  166,  213,  210,    0,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  219,  206,  205,  362,  204,  212,  362,  362,
      362,  362,  362,  211,  362,  362,  195,  155,  203,  166,
      204,  362,  198,  362,  362,  362,  362,  362,  362,  200,
      156,  189,  164,  193,  192,  194,  174,  157,  133,  136,
      112,  175,  362,   86,  362,  362,  362,    5,  169,  362,

        7,  362,  362,  332,  337,  342,  347,  349,  354,  356,
       23
    } ;

static yyconst short int yy_def[212] =
    {   0,
      204,  204,  205,  205,  205,    5,    5,    5,    5,    9,
      203,  203,  203,  203,  206,  207,  203,  203,  208,  203,
      203,  203,  203,  209,  208,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  206,
      203,  206,  207,  207,  208,  210,  203,  203,  203,  203,
      203,  203,  203,  211,  209,  206,  207,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,

      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  211,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,

      203,  203,    0,  203,  203,  203,  203,  203,  203,  203,
      203
    } ;

static yyconst short int yy_nxt[412] =
    {   0,
       12,   13,   14,   12,   15,   16,   17,   18,   71,   20,
       21,   22,   23,   24,   76,   76,   83,   83,   88,   76,
       76,   83,   83,   86,   87,   25,   92,  126,   89,   76,
       76,   96,  203,   90,  202,   73,   97,   94,   71,   93,
       26,   12,   27,  200,   98,   72,   94,   28,   12,   12,
       13,   14,   12,   15,   16,   17,   18,   84,   20,   21,
       22,   23,   24,   77,   91,  151,   78,  105,  100,  106,
       79,  101,  104,  107,   25,   72,   80,  102,  103,  108,
       91,  104,  118,  151,  116,  109,  100,  101,  119,   26,
       12,   27,   81,   82,  120,  108,   28,   12,   29,   30,

      116,   31,   32,  120,  119,   33,   34,   35,  199,  111,
       36,   37,  112,   38,  123,   39,   40,  124,   74,   41,
      113,   42,  121,  122,  125,  114,   83,   83,  123,   39,
       42,  124,   43,   29,   30,   71,   31,   32,  125,  197,
       33,   34,   35,  130,  131,   36,   37,  134,   38,  137,
       39,   40,  135,  127,   41,  136,   42,  130,  131,  162,
      148,  138,  164,  196,   39,   42,  195,   43,   44,   45,
       46,  165,   72,  128,  148,  168,   47,   48,  160,  169,
      164,  163,  128,  181,  161,  165,  172,  187,  173,  194,
      163,   49,   50,   51,  183,  189,  160,  201,  161,  181,

       49,  187,   43,   52,   53,   54,  198,  193,  192,  189,
      183,   55,   56,  201,  191,  190,  188,  186,  185,  184,
      198,  182,  180,  179,  178,  177,   57,   58,   59,  176,
      175,  174,  173,  172,  171,   57,   52,   53,   54,  170,
      167,  166,  159,  158,   55,   56,  157,  156,  155,  154,
      153,  152,  150,  149,  147,  133,  132,  129,   74,   57,
       58,   59,  203,   69,  117,  115,  110,   99,   57,   60,
       61,   62,   95,   74,   69,  203,  203,   63,   64,  203,
       65,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,   66,   67,   68,  203,  203,  203,   65,  203,

      203,   66,  139,  140,  141,  203,  142,  203,  143,  203,
      203,  203,  203,  144,  203,  145,  203,  203,  203,  203,
      203,  203,  146,  203,  203,  203,  203,  203,  203,  203,
      203,  144,   19,   19,   19,   19,   19,   12,   12,   12,
       12,   12,   70,   70,   70,   70,   70,   73,   73,  203,
       73,   73,   75,   75,   85,  203,   85,   85,   85,   76,
       76,   11,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,

      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203
    } ;

static yyconst short int yy_chk[412] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,   15,    1,
        1,    1,    1,    1,   19,   19,   22,   22,   29,   75,
       75,   21,   21,   25,   25,    1,   31,  211,   29,   25,
       25,   34,   74,   29,  201,   74,   34,   32,   70,   31,
        1,    1,    1,  198,   34,   15,   32,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,   21,    2,    2,
        2,    2,    2,   20,   30,  102,   20,   38,   36,   38,
       20,   36,   37,   38,    2,   70,   20,   36,   36,   38,
       30,   37,   73,  102,   42,   38,   36,   36,   77,    2,
        2,    2,   20,   20,   78,   38,    2,    2,    3,    3,

       42,    3,    3,   78,   77,    3,    3,    3,  194,   40,
        3,    3,   40,    3,   80,    3,    3,   81,   73,    3,
       40,    3,   79,   79,   82,   40,   83,   83,   80,    3,
        3,   81,    3,    4,    4,   86,    4,    4,   82,  191,
        4,    4,    4,   90,   91,    4,    4,   95,    4,   96,
        4,    4,   95,   88,    4,   95,    4,   90,   91,  114,
       99,   96,  115,  190,    4,    4,  189,    4,    5,    5,
        5,  116,   86,   88,   99,  120,    5,    5,  112,  120,
      115,  114,   88,  168,  112,  116,  123,  181,  123,  188,
      114,    5,    5,    5,  170,  183,  112,  199,  112,  168,

        5,  181,    5,    7,    7,    7,  192,  187,  186,  183,
      170,    7,    7,  199,  185,  184,  182,  180,  173,  171,
      192,  169,  167,  164,  158,  157,    7,    7,    7,  155,
      154,  153,  125,  124,  122,    7,    8,    8,    8,  121,
      119,  117,  111,  110,    8,    8,  109,  108,  107,  106,
      104,  103,  101,  100,   98,   93,   92,   89,   87,    8,
        8,    8,   72,   69,   65,   41,   39,   35,    8,    9,
        9,    9,   33,   16,   13,   11,    0,    9,    9,    0,
        9,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    9,    9,    9,    0,    0,    0,    9,    0,

        0,    9,   97,   97,   97,    0,   97,    0,   97,    0,
        0,    0,    0,   97,    0,   97,    0,    0,    0,    0,
        0,    0,   97,    0,    0,    0,    0,    0,    0,    0,
        0,   97,  204,  204,  204,  204,  204,  205,  205,  205,
      205,  205,  206,  206,  206,  206,  206,  207,  207,    0,
      207,  207,  208,  208,  209,    0,  209,  209,  209,  210,
      210,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,

      203,  203,  203,  203,  203,  203,  203,  203,  203,  203,
      203
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"

/**

	File:			lexer.y

	Project:		DCPU-16 Tools
	Component:		Assembler

	Authors:		James Rhodes

	Description:	Defines lexer for the assembler.

**/
	
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "parser.h"
#include "dcpu.h"

unsigned int yyalineno = 1;

char* trim_and_unescape(char* data, int mode)
{
	unsigned int i = 0, a = 0;
	char* result = malloc(strlen(data) - 1);
	memset(result, '\0', strlen(data) - 1);
	for (i = 1; i < strlen(data) - 1; i++)
	{
		if (data[i] == '\\' && data[i+1] == '"' && mode == 0)
		{
			result[a] = '"';
			i++; // skip '"'
			a++; // increment position
		}
		else if (data[i] == '\\' && data[i+1] == '\'' && mode == 1)
		{
			result[a] = '\'';
			i++; // skip '"'
			a++; // increment position
		}
		else
		{
			result[a] = data[i];
			a++; // increment position
		}
	}
	free(data);
	return result;
}

#define IN_OPCODE 1

#define IN_REG 2

#define IN_VAL 3

#define IN_NXT 4

#line 586 "lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 60 "lexer.l"


	/* Assembler keywords */

#line 742 "lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 204 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 362 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 64 "lexer.l"
yylval.number = BOUNDARY; return KEYWORD;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 65 "lexer.l"
yylval.number = EXTENSION; return KEYWORD;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 66 "lexer.l"
yylval.number = ORIGIN; return KEYWORD;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 67 "lexer.l"
yylval.number = ORIGIN; return KEYWORD;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 68 "lexer.l"
yylval.number = INCBIN; return KEYWORD;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 69 "lexer.l"
yylval.number = EXPORT; return KEYWORD;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 70 "lexer.l"
yylval.number = IMPORT; return KEYWORD;
	YY_BREAK
/* Opcodes as numbers support */
case 8:
YY_RULE_SETUP
#line 74 "lexer.l"
BEGIN(IN_OPCODE);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 75 "lexer.l"
BEGIN(INITIAL);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 76 "lexer.l"
yylval.number = OP_SET; return ADDRESS;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 77 "lexer.l"
yylval.number = OP_ADD; return ADDRESS;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 78 "lexer.l"
yylval.number = OP_SUB; return ADDRESS;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 79 "lexer.l"
yylval.number = OP_MUL; return ADDRESS;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 80 "lexer.l"
yylval.number = OP_MLI; return ADDRESS;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 81 "lexer.l"
yylval.number = OP_DIV; return ADDRESS;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 82 "lexer.l"
yylval.number = OP_DVI; return ADDRESS;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 83 "lexer.l"
yylval.number = OP_MOD; return ADDRESS;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 84 "lexer.l"
yylval.number = OP_AND; return ADDRESS;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 85 "lexer.l"
yylval.number = OP_BOR; return ADDRESS;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 86 "lexer.l"
yylval.number = OP_XOR; return ADDRESS;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 87 "lexer.l"
yylval.number = OP_SHR; return ADDRESS;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 88 "lexer.l"
yylval.number = OP_ASR; return ADDRESS;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 89 "lexer.l"
yylval.number = OP_SHL; return ADDRESS;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 90 "lexer.l"
yylval.number = OP_MVI; return ADDRESS;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 91 "lexer.l"
yylval.number = OP_IFB; return ADDRESS;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 92 "lexer.l"
yylval.number = OP_IFC; return ADDRESS;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 93 "lexer.l"
yylval.number = OP_IFE; return ADDRESS;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 94 "lexer.l"
yylval.number = OP_IFN; return ADDRESS;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 95 "lexer.l"
yylval.number = OP_IFG; return ADDRESS;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 96 "lexer.l"
yylval.number = OP_IFA; return ADDRESS;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 97 "lexer.l"
yylval.number = OP_IFL; return ADDRESS;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 98 "lexer.l"
yylval.number = OP_IFU; return ADDRESS;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 99 "lexer.l"
yylval.number = OP_ADX; return ADDRESS;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 100 "lexer.l"
yylval.number = OP_SUX; return ADDRESS;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 101 "lexer.l"
yylval.number = NBOP_JSR; return ADDRESS;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 102 "lexer.l"
yylval.number = NBOP_INT; return ADDRESS;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 103 "lexer.l"
yylval.number = NBOP_IAG; return ADDRESS;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 104 "lexer.l"
yylval.number = NBOP_IAS; return ADDRESS;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 105 "lexer.l"
yylval.number = NBOP_HWN; return ADDRESS;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 106 "lexer.l"
yylval.number = NBOP_HWQ; return ADDRESS;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 107 "lexer.l"
yylval.number = NBOP_HWI; return ADDRESS;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 109 "lexer.l"
BEGIN(IN_REG);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 110 "lexer.l"
yylval.number = REG_A; return ADDRESS;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 111 "lexer.l"
yylval.number = REG_B; return ADDRESS;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 112 "lexer.l"
yylval.number = REG_C; return ADDRESS;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 113 "lexer.l"
yylval.number = REG_X; return ADDRESS;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 114 "lexer.l"
yylval.number = REG_Y; return ADDRESS;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 115 "lexer.l"
yylval.number = REG_Z; return ADDRESS;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 116 "lexer.l"
yylval.number = REG_I; return ADDRESS;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 117 "lexer.l"
yylval.number = REG_J; return ADDRESS;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 119 "lexer.l"
BEGIN(IN_VAL);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 120 "lexer.l"
yylval.number = VAL_A; return ADDRESS;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 121 "lexer.l"
yylval.number = VAL_B; return ADDRESS;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 122 "lexer.l"
yylval.number = VAL_C; return ADDRESS;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 123 "lexer.l"
yylval.number = VAL_X; return ADDRESS;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 124 "lexer.l"
yylval.number = VAL_Y; return ADDRESS;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 125 "lexer.l"
yylval.number = VAL_Z; return ADDRESS;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 126 "lexer.l"
yylval.number = VAL_I; return ADDRESS;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 127 "lexer.l"
yylval.number = VAL_J; return ADDRESS;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 129 "lexer.l"
BEGIN(IN_NXT);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 130 "lexer.l"
yylval.number = NXT_VAL_A; return ADDRESS;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 131 "lexer.l"
yylval.number = NXT_VAL_B; return ADDRESS;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 132 "lexer.l"
yylval.number = NXT_VAL_C; return ADDRESS;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 133 "lexer.l"
yylval.number = NXT_VAL_X; return ADDRESS;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 134 "lexer.l"
yylval.number = NXT_VAL_Y; return ADDRESS;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 135 "lexer.l"
yylval.number = NXT_VAL_Z; return ADDRESS;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 136 "lexer.l"
yylval.number = NXT_VAL_I; return ADDRESS;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 137 "lexer.l"
yylval.number = NXT_VAL_J; return ADDRESS;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 138 "lexer.l"
yylval.number = NXT_LIT; return ADDRESS;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 140 "lexer.l"
yylval.number = PUSH_POP; return ADDRESS;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 141 "lexer.l"
yylval.number = PUSH_POP; return ADDRESS;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 142 "lexer.l"
yylval.number = PEEK; return ADDRESS;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 143 "lexer.l"
yylval.number = PICK; return ADDRESS;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 144 "lexer.l"
yylval.number = SP; return ADDRESS;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 145 "lexer.l"
yylval.number = PC; return ADDRESS;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 146 "lexer.l"
yylval.number = EX; return ADDRESS;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 147 "lexer.l"
yylval.number = IA; return ADDRESS;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 148 "lexer.l"
yylval.number = NXT; return ADDRESS;
	YY_BREAK
/* General stuff */
case 79:
YY_RULE_SETUP
#line 152 "lexer.l"
yylval.string = strdup(yytext); return WORD;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 153 "lexer.l"
yylval.number = strtoul(yytext, NULL, 16); return ADDRESS;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 154 "lexer.l"
yylval.number = strtoul(yytext, NULL, 10); return ADDRESS;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 155 "lexer.l"
{ yylval.string = trim_and_unescape(strdup(yytext), 1); return CHARACTER; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 156 "lexer.l"
{ yylval.string = trim_and_unescape(strdup(yytext), 0); return STRING; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 157 "lexer.l"
return COMMA;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 158 "lexer.l"
return BRACKET_OPEN;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 159 "lexer.l"
return BRACKET_CLOSE;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 160 "lexer.l"
return COLON;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 161 "lexer.l"
return ADD;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 163 "lexer.l"
yyalineno++; return NEWLINE;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 164 "lexer.l"
/* ignore comments */;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 165 "lexer.l"
/* ignore whitespace */;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 167 "lexer.l"
ECHO;
	YY_BREAK
#line 1287 "lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_OPCODE):
case YY_STATE_EOF(IN_REG):
case YY_STATE_EOF(IN_VAL):
case YY_STATE_EOF(IN_NXT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 204 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 204 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 203);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 167 "lexer.l"

